In [1]:
a = 20
b = 30
print(a+b)

50


In [2]:
name = '이지우'
print('안녕하세요 {}님 데이터전처리 수업에 오신것을 환영합니다.'.format(name))

안녕하세요 이지우님 데이터전처리 수업에 오신것을 환영합니다.


In [3]:
import numpy as np

lst = [1,5,5,7,3,6,88,12,5,74,4,8,64,2,7,89,33,1,6,8,1,5,6,7]
arr = np.array(lst)

In [4]:
lst

[1, 5, 5, 7, 3, 6, 88, 12, 5, 74, 4, 8, 64, 2, 7, 89, 33, 1, 6, 8, 1, 5, 6, 7]

In [5]:
arr

array([ 1,  5,  5,  7,  3,  6, 88, 12,  5, 74,  4,  8, 64,  2,  7, 89, 33,
        1,  6,  8,  1,  5,  6,  7])

In [6]:
print(arr[:5]+arr[5:10])

[ 7 93 17 12 77]


In [7]:
lst.index(88)

6

In [8]:
lst1 = ['Jone-30', 'Park-30', 'Kim-20', 'Lee-10', 'Oh-32', 'Kang-25']

In [9]:
lst1[3][:3]

'Lee'

In [10]:
lst2 = ['데이터 전치리 수업, 입니다.', 'Data Preprocesing']

In [11]:
lst2[0] = lst2[0].replace('데이터 전치리 수업, 입니다.', '데이터 전처리 수업입니다.')
lst2[1] = lst2[1].replace('Data Preprocesing', 'Data Preprocessing')

In [12]:
lst2

['데이터 전처리 수업입니다.', 'Data Preprocessing']

In [14]:
arr1 = np.array([1,2,3,4])

In [15]:
arr1

array([1, 2, 3, 4])