In [118]:
import numpy as np
import pandas as pd

In [119]:
lst = [1, 100, 2, 5, 6, 7, 8, 9]

In [120]:
arr = np.array(lst)

In [121]:
arr = np.delete(arr, lst.index(100))
arr = np.insert(arr, 2, 3)
arr = np.insert(arr, 3, 4)
arr = np.append(arr, 10)
arr = np.append(arr, 11)

In [122]:
lst.pop(lst.index(100))
lst.insert(2, 3)
lst.insert(3, 4)
lst.append(10)
lst.append(11)
arr2 = np.array(lst)

In [123]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [124]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [125]:
A = arr[arr <= 5]
B = arr[arr < 4]

In [126]:
A

array([1, 2, 3, 4, 5])

In [127]:
B

array([1, 2, 3])

In [128]:
name_phone = { '이름' : ['가', '나', '다', '라', '마'],
              '전화번호' : [0, 1, 2, 3, 4]}

In [129]:
df = pd.DataFrame(name_phone)

In [130]:
df

이름  전화번호
0  가     0
1  나     1
2  다     2
3  라     3
4  마     4

In [131]:
df2 = pd.read_csv('test.csv', encoding='cp949')

In [132]:
df2

연령     학력  성과능력  성과태도
0  26~30세  대학원졸업     5     4
1  31세 이상  대학교졸업     4     3
2  31세 이상  전문대졸업     4     2
3  26~30세  대학원졸업     4     4
4  20~25세  대학교졸업     4     4